FROM apache/spark:3.5.1-python3

USER root

WORKDIR /app

COPY producer/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY spark/ .

# The entrypoint will depend on spark-submit, handled by docker-compose usually.
# But we provide the code for custom image generation.
